### ISSUE TITLE
PDF/EPS export of shared model yields "UNAUTHORIZED" error

### ISSUE THREAD

**Issue by laena** [troeger/fuzzed#101]
Reproducible for multiple shared graphs: PDF and EPS export trigger the error, but GraphML and LaTeX export work as usual.

**Comment by troeger** [comment]
Looks like a duplicate of #16. Sorry, no timing for coding at the moment. Can you provide a patch?

**Comment by laena** [comment]
Sorry - seems like I'm unable to use the issue search properly. I'll try to find a fix, but not sure when that will be...
